<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'egyg33k.csv.writer' shared service.

include_once $this->targetDirs[3].'\\vendor\\egyg33k\\csv-bundle\\Services\\Writer.php';

return $this->services['egyg33k.csv.writer'] = new \Egyg33k\CsvBundle\Services\Writer();
