<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'history.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\doctrine\\event-manager\\lib\\Doctrine\\Common\\EventSubscriber.php';
include_once $this->targetDirs[3].'\\vendor\\mrad\\notifications-bundle\\SBC\\NotificationsBundle\\EventListener\\HistoryService.php';

return $this->services['history.service'] = new \SBC\NotificationsBundle\EventListener\HistoryService($this);
