<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC1esw3e\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC1esw3e/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerC1esw3e.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerC1esw3e\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerC1esw3e\appProdProjectContainer([
    'container.build_hash' => 'C1esw3e',
    'container.build_id' => '12d9b182',
    'container.build_time' => 1589119779,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC1esw3e');
