<?php

namespace CommandeBundle\Repository;

/**
 * cmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cmdRepository extends \Doctrine\ORM\EntityRepository
{
}
