<?php

namespace CommandeBundle\Repository;

/**
 * lignecmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lignecmdRepository extends \Doctrine\ORM\EntityRepository
{

    public function findkey($key){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM CommandeBundle:lignecmd p
                WHERE p.produit_id = key'
            )
            ->setParameter('key', '%'.$key.'%')
            ->getResult();
    }


}
