<?php

namespace ProduitBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBikeByName($nameBike){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM ProduitBundle:Produit p
                WHERE p.libelle LIKE :nameBike'
            )
            ->setParameter('nameBike', '%'.$nameBike.'%')
            ->getResult();
    }



    public function findProduitsHorsStock(){
        return $this->getEntityManager()->createQuery(
                            'SELECT p 
                                  FROM ProduitBundle:Produit p
                                  WHERE p.qte = 0')->getResult();
    }

    public function findProduitsEnReptureDeStock(){
        return $this->getEntityManager()->createQuery(
            'SELECT p 
                                  FROM ProduitBundle:Produit p
                                  WHERE p.qte > 0 AND p.qte<10')->getResult();
    }

    public function findById($id){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM ProduitBundle:Produit p
                WHERE p.id = :id'
            )
            ->setParameter('id', '%'.$id.'%')
            ->getResult();
    }

}
