<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDrllobd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDrllobd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDrllobd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDrllobd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDrllobd\appDevDebugProjectContainer([
    'container.build_hash' => 'Drllobd',
    'container.build_id' => '2ce0fa93',
    'container.build_time' => 1591788496,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDrllobd');
