<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG6rwavg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG6rwavg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerG6rwavg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerG6rwavg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerG6rwavg\appDevDebugProjectContainer([
    'container.build_hash' => 'G6rwavg',
    'container.build_id' => 'c8063ac2',
    'container.build_time' => 1592227868,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG6rwavg');
